### ISSUE TITLE
Post library not working with blender 3.5

### ISSUE THREAD

**Issue by okikiola12** [scaredyfish/blender-rhubarb-lipsync#58]
Rhubarb is not working with the latest version of blender 3.5. The post lib is missing, and when click the items is missing

**Comment by BhasmaSur** [comment]
facing the same issue, getting this error :

    if context.object.pose_library:
AttributeError: 'Object' object has no attribute 'pose_library'

since pose library is moved inside asset browser now, this if condition gets false and rhubarb shows nothing in the drop down.

**Comment by okikiola12** [comment]
Yh, there is need to update line 21 of the code.
I have since downgraded back to 3.4 though

**Comment by amitkumardagar** [comment]
im facing same problem with blender 3.5

**Comment by NeilArmstrong69** [comment]
Thank you for this fantastic Add. I teach Blender and I used the Addon for lipsync. At this moment it became unfeasible to use, because the problem is that in 3.5 there is no longer PoseLib. Even with the version that uses properties, the character cannot be used in another file via link, as you lose access to other mouths and are tied to lipsync only, which makes it unfeasible to use for more complex animations with Rig.
I would love to be able to use it again.

**Comment by ProdigeLFK** [comment]
> Il faut mettre à jour la ligne 21 du code. Je suis depuis rétrogradé à 3,4

Salut, Comment faire cela, comment mette à jour là ligne 21 ?
